"""add of tag models

Revision ID: 66b657ae1629
Revises: 91f7e443093d
Create Date: 2024-11-01 13:28:59.184599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66b657ae1629'
down_revision: Union[str, None] = '91f7e443093d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('update_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('books', 'updated_at')
    op.add_column('reviews', sa.Column('update_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('reviews', 'updated_at')
    op.add_column('users', sa.Column('update_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'update_at')
    op.add_column('reviews', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'update_at')
    op.add_column('books', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('books', 'update_at')
    # ### end Alembic commands ###
