"""add user's uid foreign key on books table

Revision ID: 94af4145b3f1
Revises: 5bdeceae1166
Create Date: 2024-10-28 15:35:48.613306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '94af4145b3f1'
down_revision: Union[str, None] = '5bdeceae1166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_uuid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['user_uuid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'user_uuid')
    # ### end Alembic commands ###
