"""modification of user_uuid, to user_uid

Revision ID: c327e49dfb95
Revises: 94af4145b3f1
Create Date: 2024-10-28 15:53:50.050387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c327e49dfb95'
down_revision: Union[str, None] = '94af4145b3f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.drop_constraint('books_user_uuid_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['user_uid'], ['uid'])
    op.drop_column('books', 'user_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_uuid', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_user_uuid_fkey', 'books', 'users', ['user_uuid'], ['uid'])
    op.drop_column('books', 'user_uid')
    # ### end Alembic commands ###
