"""reverse

Revision ID: f7c378ebe983
Revises: 08926291b71d
Create Date: 2024-11-01 13:04:16.022560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7c378ebe983'
down_revision: Union[str, None] = '08926291b71d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booktag')
    op.drop_table('tags')
    op.add_column('books', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('books', 'update_at')
    op.add_column('reviews', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('reviews', 'update_at')
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('users', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'updated_at')
    op.add_column('reviews', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'updated_at')
    op.add_column('books', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('books', 'updated_at')
    op.create_table('tags',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid', name='tags_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('booktag',
    sa.Column('book_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.uid'], name='booktag_book_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.uid'], name='booktag_tag_id_fkey'),
    sa.PrimaryKeyConstraint('book_id', 'tag_id', name='booktag_pkey')
    )
    # ### end Alembic commands ###
